name: Deployment Trigger

on:
  push:
    branches:
      - main

jobs:
  trigger-deployment:
    steps:
    - name: Trigger Deployment
      uses: satak/webrequest-action@master
      with:
        url: https://ddvis.oii.ox.ac.uk/deploy?key=${{ secrets.DEPLOYMENT_KEY }}
        method: GET

